### ISSUE TITLE
Problem with `supportedOrganisms()`

### ISSUE THREAD

**Issue by JSBoey** [GenomicsAotearoa/RNA-seq-workshop-on-demand#1]
The underlying code uses `rtracklayer` that has problems (possibly deprecation?) with [accessing UCSC](https://github.com/lawremi/rtracklayer/issues/113)

**Comment by DininduSenanayake** [comment]
this will trigger 
```r
O.wall=goseq(pwf, "sacCer1", "ensGene")
Fetching GO annotations...
Error in library(paste(orgstring, "db", sep = "."), character.only = TRUE) : 
  there is no package called 'org.Sc.sgd.db'
```

### Solution
```r
BiocManager::install("org.Sc.sgd.db")
```

**Comment by DininduSenanayake** [comment]
This was fixed in https://github.com/nesi/training-environment-rstudio-rnaseq-app/commit/3791e339da5dcafad5cf468ccbaa08d12de20754
